spring:
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: http://localhost:7070/realms/Example
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8097

jwt:
  auth:
    converter:
      resource-id: spring-boot-test
      principle-attribute: preferred_username